name: Linux
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Linux:
    runs-on: ubuntu-24.04
    strategy:      
      matrix:
        config:
        - {
            options: "-DCMAKE_BUILD_TYPE=Debug"
          }
        - {
            options: "-DBUILD_SHARED_LIBS=ON"
          }
        gcc-version: [12]
        include:
        - gcc-version: 14

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: get-gcc
      run: |
        if [ -z $(type -P gcc-${{ matrix.gcc-version }}) ]; then
           sudo apt-get install gcc-${{ matrix.gcc-version }} gfortran-${{ matrix.gcc-version }}
        fi

    - name: build
      run: |
        export CC=gcc-${{ matrix.gcc-version }} ; export FC=gfortran-${{ matrix.gcc-version }}
        cmake -B build ${{ matrix.config.options }} -DCMAKE_INSTALL_PREFIX=~/install
        cmake --build build --parallel 2 --verbose
    
    - name: test
      run: |
        set -x
        ctest --test-dir build --verbose --output-on-failure --rerun-failed
        cmake --install build
        if [ "${{ matrix.config.options }}" = "-DBUILD_SHARED_LIBS=ON" ]; then
           ls -l ~/install/lib/lib*.so || exit 1
        else
           ls -l ~/install/lib/lib*.a || exit 1
        fi
