name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      CC: gcc-12

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: |
        cmake -B build
        cmake --build build --parallel 2 --verbose
    
    - name: test
      run: |
        ctest --test-dir build --verbose --output-on-failure --rerun-failed 

